name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    
    - name: Cache RubyGems
      uses: actions/cache@v
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gem-

    - name: Install dependencies
      run: gem install bundler && cd Wegli && bundle install && pod install

    - name: Run tests
      run: bundle exec fastlane test
