name: CI

on:
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    
    # Install dependencies
    - name: Bundle install
      run: cd Wegli && bundle install
    - name: Install Pods
      run: pod install

    - name: Run tests
      run: bundle exec fastlane test
